%.eepic : %.xp
	epix -I. $<

%.pdf : %.eepic
	elaps -I. --pdf $<

IMAGE_FILES = 018a.pdf \
	019a.pdf \
	019b.pdf \
	022a.pdf \
	023a.pdf \
	040a.pdf \
	040b.pdf \
	088a.pdf \
	090a.pdf \
	091a.pdf \
	091b.pdf \
	091c.pdf \
	092a.pdf \
	092b.pdf \
	093a.pdf \
	093b.pdf \
	094a.pdf \
	094b.pdf \
	095a.pdf \
	096a.pdf \
	096b.pdf \
	097a.pdf \
	097b.pdf \
	099a.pdf \
	099b.pdf \
	099c.pdf \
	105a.pdf \
	106a.pdf \
	113a.pdf \
	114a.pdf \
	120a.pdf \
	124a.pdf \
	124b.pdf \
	125a.pdf \
	126a.pdf \
	126b.pdf \
	150a.pdf \
	151a.pdf \
	158a.pdf \
	158b.pdf \
	167a.pdf \
	167b.pdf \
	168a.pdf \
	177a.pdf \
	179a.pdf \
	179b.pdf \
	195a.pdf \
	197a.pdf \
	197b.pdf \
	198a.pdf \
	198b.pdf \
	200a1.pdf \
	200a2.pdf \
	200a3.pdf \
	200a4.pdf \
	200a5.pdf \
	200a6.pdf \
	200b.pdf \
	201a.pdf \
	202a.pdf \
	218a.pdf \
	219a.pdf \
	223a.pdf \
	224a.pdf \
	225a.pdf \
	226a.pdf \
	227a.pdf \
	227b.pdf \
	228a.pdf \
	229a.pdf \
	231a.pdf \
	233a.pdf \
	235a.pdf




all: $(IMAGE_FILES)
